
LANGUAGES = {
  'ar': 'Arabic',
  'da': 'Danish',
  'de': 'German',
  'en': 'English',
  'es': 'Spanish',
  'fr': 'French',
  'he': 'Hebrew',
  'id': 'Indonesian',
  'it': 'Italian',
  'ja': 'Japanese',
  'la': 'Latin',
  'nl': 'Dutch',
  'nn': 'Norwegian',
  'pl': 'Polish',
  'ro': 'Romanian',
  'sl': 'Slovenian',
  'zh': 'Chinese',
  'hr': 'Croatian',
  'ca': 'Catalan',
  'et': 'Estonian',
  'pt': 'Portuguese',
  'sv': 'Swedish',
  'gl': 'Galician',
  'bg': 'Bulgarian',
  'ko': 'Korean',
  'fi': 'Finnish',
}

